import type { CanonicalLocationRecord } from "./contracts.ts";

export type ImportMode = "validate-only" | "dry-run" | "apply";

export type LocationRow = {
  id: string;
  name: string;
  description: string;
  category: string;
  region: string;
  address: string;
  latitude: number;
  longitude: number;
  permit_type: string;
  contact_name: string | null;
  contact_phone: string | null;
  permit_note: string | null;
  permit_source: string;
  permit_source_url: string;
  permit_reference_date: string | null;
  permit_last_verified_at: string | null;
  source_url: string;
  import_batch: string;
  reference_date: string | null;
  last_verified_at: string | null;
};

// No `id` field: parking.id is generated by its column default
// (gen_random_uuid()) on first insert and left untouched by later upserts,
// which target (location_id, name) instead -- see
// supabase/migrations/20260929000000_parking_upsert_key.sql for why.
export type ParkingRow = {
  location_id: string;
  relationship: "on_site" | "nearby";
  name: string;
  latitude: number;
  longitude: number;
  capacity: number | null;
  opening_hours: string | null;
  price_info: string | null;
  source: string | null;
  source_url: string | null;
  reference_date: string | null;
  last_verified_at: string | null;
};

export type ExistingParkingKey = { location_id: string; name: string };

export interface LocationImportDatabase {
  findExistingLocationIds(ids: string[]): Promise<string[]>;
  findExistingParkingKeys(locationIds: string[]): Promise<ExistingParkingKey[]>;
  upsertLocations(rows: LocationRow[]): Promise<void>;
  upsertParking(rows: ParkingRow[]): Promise<void>;
}

export type ImportCounts = { validated: number; existing: number; toInsert: number; written: number };
export type ImportResult = { mode: ImportMode; locations: ImportCounts; parking: ImportCounts };

function requireId(record: CanonicalLocationRecord): string {
  if (!record.id) {
    throw new Error(`Location "${record.name}" has no id -- did an unvalidated record reach the importer?`);
  }
  return record.id;
}

function toLocationRow(record: CanonicalLocationRecord): LocationRow {
  return {
    id: requireId(record),
    name: record.name,
    description: record.description,
    category: record.category,
    region: record.region,
    address: record.address,
    latitude: record.latitude,
    longitude: record.longitude,
    permit_type: record.permit.type,
    contact_name: record.permit.contactName,
    contact_phone: record.permit.contactPhone,
    permit_note: record.permit.note,
    permit_source: record.permit.provenance.source,
    permit_source_url: record.permit.provenance.sourceUrl,
    permit_reference_date: record.permit.provenance.referenceDate,
    permit_last_verified_at: record.permit.provenance.lastVerifiedAt,
    source_url: record.sourceUrl,
    import_batch: record.provenance.source,
    reference_date: record.provenance.referenceDate,
    last_verified_at: record.provenance.lastVerifiedAt,
  };
}

function toParkingRows(record: CanonicalLocationRecord): ParkingRow[] {
  const locationId = requireId(record);
  return record.parking.map((parking) => ({
    location_id: locationId,
    relationship: parking.relationship,
    name: parking.name,
    latitude: parking.latitude,
    longitude: parking.longitude,
    capacity: parking.capacity,
    opening_hours: parking.openingHours,
    price_info: parking.priceInfo,
    source: parking.provenance.source,
    source_url: parking.provenance.sourceUrl,
    reference_date: parking.provenance.referenceDate,
    last_verified_at: parking.provenance.lastVerifiedAt,
  }));
}

function chunks<T>(values: T[], size: number): T[][] {
  const result: T[][] = [];
  for (let index = 0; index < values.length; index += size) result.push(values.slice(index, index + size));
  return result;
}

/** Builds insertable rows from already-validated records. Defensively re-checks for a duplicate id within this batch even though scripts/data/validator.ts already rejects duplicates dataset-wide. */
export function buildImportRows(records: CanonicalLocationRecord[]): { locationRows: LocationRow[]; parkingRows: ParkingRow[] } {
  const seenIds = new Set<string>();
  const locationRows: LocationRow[] = [];
  const parkingRows: ParkingRow[] = [];
  for (const record of records) {
    const id = requireId(record);
    if (seenIds.has(id)) throw new Error(`Duplicate location id in import batch: ${id}`);
    seenIds.add(id);
    locationRows.push(toLocationRow(record));
    parkingRows.push(...toParkingRows(record));
  }
  return { locationRows, parkingRows };
}

export async function importLocationDataset(
  records: CanonicalLocationRecord[],
  mode: ImportMode,
  batchSize: number,
  database?: LocationImportDatabase,
): Promise<ImportResult> {
  if (!Number.isInteger(batchSize) || batchSize < 1 || batchSize > 500) {
    throw new Error("Import batch size must be an integer between 1 and 500");
  }
  const { locationRows, parkingRows } = buildImportRows(records);

  if (mode === "validate-only") {
    return {
      mode,
      locations: { validated: locationRows.length, existing: 0, toInsert: locationRows.length, written: 0 },
      parking: { validated: parkingRows.length, existing: 0, toInsert: parkingRows.length, written: 0 },
    };
  }
  if (!database) throw new Error(`Database connection is required for ${mode}`);

  const existingLocationIds: string[] = [];
  for (const batch of chunks(locationRows.map((row) => row.id), batchSize)) {
    existingLocationIds.push(...await database.findExistingLocationIds(batch));
  }
  const existingLocationIdSet = new Set(existingLocationIds);

  const locationIdsInBatch = [...new Set(locationRows.map((row) => row.id))];
  const existingParkingKeys: ExistingParkingKey[] = [];
  for (const batch of chunks(locationIdsInBatch, batchSize)) {
    existingParkingKeys.push(...await database.findExistingParkingKeys(batch));
  }
  const existingParkingKeySet = new Set(existingParkingKeys.map((key) => `${key.location_id}\u0000${key.name}`));
  const existingParkingCount = parkingRows.filter(
    (row) => existingParkingKeySet.has(`${row.location_id}\u0000${row.name}`),
  ).length;

  const counts: ImportResult = {
    mode,
    locations: {
      validated: locationRows.length,
      existing: existingLocationIdSet.size,
      toInsert: locationRows.length - existingLocationIdSet.size,
      written: 0,
    },
    parking: {
      validated: parkingRows.length,
      existing: existingParkingCount,
      toInsert: parkingRows.length - existingParkingCount,
      written: 0,
    },
  };
  if (mode === "dry-run") return counts;

  // locations before parking: parking.location_id is a foreign key.
  for (const batch of chunks(locationRows, batchSize)) await database.upsertLocations(batch);
  for (const batch of chunks(parkingRows, batchSize)) await database.upsertParking(batch);

  counts.locations.written = locationRows.length;
  counts.parking.written = parkingRows.length;
  return counts;
}
