-- Backend-owned follow-up: gives scripts/data's new locations+parking
-- importer (scripts/data/location-importer.ts) a real upsert target for
-- parking, so re-running the same input never creates duplicate rows.
--
-- locations already has a natural, deterministic upsert key: its own `id`,
-- which scripts/data/normalizer.ts passes through unchanged from the source
-- dataset (see docs/database.md and the report for this change). Parking
-- entries have no equivalent -- CanonicalParkingRecord.id
-- (scripts/data/contracts.ts) is optional, not validated as a UUID by
-- scripts/data/validator.ts, and not guaranteed present, so it is not used
-- as the parking.id primary key here. Instead: a parking spot's name is
-- required and, in practice, unique among the parking options for one
-- location, so (location_id, name) is the upsert key. `parking.id` keeps
-- being generated by its column default (gen_random_uuid()) on first
-- insert and is left untouched by later upserts, since ON CONFLICT
-- (location_id, name) DO UPDATE never targets or overwrites it.
alter table public.parking
  add constraint parking_location_id_name_key unique (location_id, name);
